### PR TITLE
Surface errors through pstore

### PR DESCRIPTION
**Pull request by srizzling**
Its kinda difficult to debug errors with `pstore` since the underlying error is gobbled up, and not surfaced through the logs. This change should surface those errors especially if wasn't able to successfully decrypt the parameter.

I tested a few times and it seemed it to work for my use cases, but might need to be tested with the tags..

I also have included some changes to improve the output of the shell documentation.. just cause it bugged me that it pointed to Cobra.

### CODE REVIEW

**Comment by endofcake** [comment]
@aidansteele

**Comment by aidansteele** [comment]
Champion! 💯

**Comment by aidansteele** [comment]
Released in version 1.5.0: https://github.com/glassechidna/pstore/releases/tag/1.5.0

**Comment by srizzling** [comment]
Thank you mr @aidansteele!

**Pull request merged**
